include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_void_async
    - unawaited_futures
    - unnecessary_await_in_return

analyzer:
  exclude:
    - '**/*.g.dart'
    - 'lib/shared/theme/app_theme.dart'
    - 'lib/injector.config.dart'
    - 'lib/generated/*.dart'
  plugins:
    - dart_code_metrics

dart_code_metrics:
  rules:
    - prefer-trailing-comma